version: '3.8'
services:
  postgres:
    container_name: spring_demo_db
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=demodb
    ports:
      - "5122:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    container_name: spring_demo_app    
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    dns:
      - 8.8.8.8
    ports:
      - "8088:8080"