# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs - Reusable packages for use.
orbs:
  docker: circleci/docker@2.6.0
  # heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@2.1.0

# Jobs - Set of instructions / functions.
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build: # Job name.
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker: # Environment.
      # Specify the version you desire here.
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/openjdk:21.0.2
        environment:
          PGHOST: 127.0.0.1
      - image: cimg/postgres:16.2.0

    # Add steps to the job.
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - restore_cache # Restore the saved cache after the first run or if 'pom.xml' has changed.
        # key: cireclci-demo-java-spring-{{checksum "pom.xml"}}

      - run: |
          echo "Installing dependencies..."
          java --version

  test:
    docker: # Environment.
      - image: cimg/openjdk:21.0.2

    steps:
      - checkout
      - run: |
          echo "Running tests..."
          java --version

  scan:
    docker:
      # - image: cimg/node:20.12.2
      # - image: cimg/node:current
      - image: cimg/base:current

    environment: # The environment allows us to create an environment for the job and allows us to create custom environment variables.
      IMAGE_NAME: nhkhai/education-space

    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME . # $IMAGE_NAME gets the value from the environment we created above.
      - snyk/scan: # This triggers the Snyk scan using the preconfigured SNYK_TOKEN environmental variable.
          docker-image-name: $IMAGE_NAME # The image name, if scanning a container image.
          fail-on-issues: false # This specifies if builds should be failed or continued based on issues found by Snyk. If false, the failure is hidden and marked as a pass.
          severity-threshold: high # Only report vulnerabilities of provided level or higher (low/medium/high/critical). If param is not present, the default value is low.

  publish: # Also known as the build-and-push.
    executor: docker/docker # Define the execution environment in which the steps of a job will run.

    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build: # Build the image.
          image: nhkhai/education-space
          # tag: v1.0.1
          tag: latest # Consider setting this dynamically based on the tag using env vars or CircleCI parameters.
          # tag: ${CIRCLE_TAG:-latest}  # Use the tag name if triggered by a tag, otherwise use 'latest'.
      - docker/push: # Pushes the image to the specified account in the environment variables.
          image: nhkhai/education-space
          # tag: v1.0.1
          tag: latest # Consider setting this dynamically based on the tag using env vars or CircleCI parameters.
          # tag: ${CIRCLE_TAG:-latest}  # Use the tag name if triggered by a tag, otherwise use 'latest'.

  # deploy:
  #   docker:
  #       - image: cimg/node:20.12.2
  #
  #   steps:
  #       - checkout
  #       - setup_remote_docker
  #       - heroku/install
  #       - run:
  #           name: Heroku Container Push
  #           command: |
  #               heroku container:login
  #               heroku container:push web -a nhkhai-node-app-for-devops
  #               heroku container:release web -a nhkhai-node-app-for-devops
  deploy:
    docker:
      # - image: cimg/deploy:2024.03
      # - image: cimg/deploy:2024.03-node
      # - image: cimg/base:current-22.04
      - image: cimg/base:current

    steps:
      # - checkout
      # - setup_remote_docker
      - run:
          name: Render Deploy Hook
          command: |
            curl "$RENDER_DEPLOY_HOOK_URL"

# Workflow - Defines what sequence will the jobs run.
# Orchestrate jobs using workflows.
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  ci_flow: # Workflow name. This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      # - build:
      #     filters:
      #       branches:
      #         only:
      #           - main
      #         ignore:
      #           - release

      - test:
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - main
          #     ignore:
          #       - release

      # The Snyk security scan job.
      - scan:
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - main
          #     ignore:
          #       - release

      - publish:
          # Ensure that the dependency job(s) are able to run (watch out for branch filtering affecting this), else publish and deploy (depends on publish) will not run at all.
          requires:
            - test
            - scan
          filters:
            # tags:
            #   only: /^v[0-9]+\.[0-9]+\.[0-9]+$/ # Ensure this job runs only for semantically versioned tags. This regex pattern matches semantic versioning tags (e.g., v1.0.0, v2.1.3).
            branches:
              only:
                - release

      - deploy:
          requires:
            - publish
          filters:
            # tags:
            #   only: /^v[0-9]+\.[0-9]+\.[0-9]+$/ # Ensure this job runs only for semantically versioned tags. This regex pattern matches semantic versioning tags (e.g., v1.0.0, v2.1.3).
            branches:
              only:
                - release

  cicd_flow:
    - deploy:
        requires:
          - publish
        filters:
          # tags:
          #   only: /^v[0-9]+\.[0-9]+\.[0-9]+$/ # Ensure this job runs only for semantically versioned tags. This regex pattern matches semantic versioning tags (e.g., v1.0.0, v2.1.3).
          branches:
            only:
              - release
